version: '3.3'
services:
  app:
    build: .
    volumes:
      - .:/core
    ports:
      - 8000:8000
    container_name: fastapi_core
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 4
  
  nginxcustomer:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app