"""relationship second

Revision ID: 74c349b1368e
Revises: 
Create Date: 2022-07-09 18:38:47.583951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c349b1368e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'owner_id')
    # ### end Alembic commands ###
